# Generated by Django 2.0.5 on 2018-07-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmelo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tag',
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
